### ISSUE TITLE
Anyterm for Config UI X 

### ISSUE THREAD

**Issue by razer4908** [oznu/homebridge-config-ui-x#110]
Hi, 

Do you think it is possible to implement Anyterm for an "in-Browser" administration of your Homebridge Device e.g Raspberry Pi ?

**Comment by oznu** [comment]
When running in docker this plugin actually already provides this exact feature. I didn't enable it for other platforms as I thought it might present a security risk that users may not particularly like if I added the feature with an update.

**Comment by razer4908** [comment]
Im not too much into programming but do you think it is possible to implement this feature if you want, so if you do not want it you have to uncheck a checkbox for example ?

**Comment by palasinio** [comment]
Is it difficult to install AnyTerm on the PI? Or is it for a single webinterface?

**Comment by oznu** [comment]
@razer4908 - I have enabled this. However, it's not a simple `config.json` flag, since this could be toggled from inside the UI itself which would defeat the purpose of having it disabled by default.

You'll need to run the process with the environment variable `HOMEBRIDGE_CONFIG_UI_TERMINAL=1`.

If you're running with systemd you can add this to your `/etc/default/homebridge` file.

Available in 3.8.3.
