### ISSUE TITLE
Multiple security issues

### ISSUE THREAD

**Issue by grawlinson** [oznu/homebridge-config-ui-x#1167]
There are multiple security issues from both a packaging and operational security perspective.

## Issues upon invoking `hb-service install`

* Adding a system user that has access to a shell.
* Modifying `/etc/sudoers`.
* Adding files/folders throughout the system:
  * systemd service file
  * `/etc/hb-service` directory
* The generated systemd service has excessive permissions granted to it, e.g. `CapabilityBoundingSet`/`AmbientCapabilities` options. It also needs a fair amount of security hardening to prevent privilege escalation.

## Issues at run-time

* Providing a sudo configuration option and not respecting it.
* Invoking ~~npm via~~ sudo. Just don't use sudo.
* Invoking npm with deprecated flag `--unsafe-perm`.
* Invoking `npm install` with `--global` flag. Apart from the glaringly obvious security concerns, this pollutes the global namespace that users aren't aware of.

## General issues

* Assuming every Linux distribution follows Debian-specific guidelines. The directory `/etc/default` does not exactly exist on other Linux distributions, nor does `run-parts`.
* Upstream systemd has stated that the `EnvironmentFile` directive [should not have been implemented][envfile] in the first place, and to prefer using the `Environment=Key=Value` [directive][env-kv] in systemd service files.
* Updating Node.js. For a project like this, that's massively out of scope. Leave that up to the distribution or let the sysadmin manage it via alternative implementations such as nvm, pm2, etc.

## Solutions/Mitigations

* Don't use sudo. Ever.
* System accounts should use [per-user global npm][npmg-no-sudo] installs.
* Don't modify `/etc/sudoers`.
* Set the system user's home directory to `/var/lib/homebridge`.
* Don't pollute the global namespace, keep all generated files/directories within the system user's home directory.

[npmg-no-sudo]:https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md
[envfile]:https://lists.freedesktop.org/archives/systemd-devel/2015-December/035236.html
[env-kv]:https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment=

**Comment by oznu** [comment]
> adding systemd service file

hb-service is a managed setup, it is expected to create a system service including a systemd service file to operate as expected.

The alternative is having users create their own systemd services etc. which caused no end of issues for new users.

> Invoking npm via sudo. Just don't use sudo.
> System accounts should use per-user global npm installs.
> Invoking npm install with --global flag. 

I agree this is less than ideal. The use of sudo on Linux is required to maintain backwards compatibility with existing installs from before the hb-service installer existed. Unfortunately there are too many plugins and guides that tell users to install plugins manually with `sudo npm install` moving away from this will be challenging. 

This is a trade off as I don't want to get bombarded with questions and issues regarding things not working.

> Providing a sudo configuration option and not respecting it.

The sudo option is hidden when running with `hb-service` as it's a managed setup. If you choose not to use `hb-service` as a service manager, then the sudo config option is respected.

> Invoking npm with deprecated flag --unsafe-perm

This is required for *any* plugin that has native modules, as of npm 7 it's deprecated, and is the default behaviour so removing it will not change anything here.

> Updating Node.js. For a project like this, that's massively out of scope. Leave that up to the distribution or let the sysadmin manage it via alternative implementations such as nvm, pm2, etc.

Before adding this feature about half of issues users raised came down to updating Node.js in an incorrect way, often resulting in multiple copies of Node installed etc. The installer attempts to install using the same method the user originally used to install (NodeSource for most systems, binary for arm32v6 as NodeSource does not support this architecture).

Since adding this feature, such issues have reduced to near zero.

> Assuming every Linux distribution follows Debian-specific guidelines. The directory /etc/default does not exactly exist on other Linux distributions, nor does run-parts

Agree, we would add distribution checks before proceeding. The install guides only exist for Debian-based, RedHat-based and Arch Linux systems which do include these things as part of a base install.

**Comment by grawlinson** [comment]
This issue needs to stay open until all these concerns are resolved.

**Comment by oznu** [comment]
I think this would be better addressed as pull requests for each individual issue raised that is feasible to resolve.
