### ISSUE TITLE
hb-service listening on port 5353 which conflicts with avahi daemon

### ISSUE THREAD

**Issue by introns-bungles** [oznu/homebridge-config-ui-x#1280]
See: https://github.com/homebridge/homebridge/issues/3077

**Describe The Bug:**

**To Reproduce:**

1. Use `avahi` as systemwide mdns resolver.
2. Select `avahi` as `"advertiser": "avahi",` in homebridge.
3. Check output of `ss -tulwpn | grep 5353`.

**Expected behavior:**
When `avahi` is selected as advertiser `hb-service` should not listen on port `5353`.

**Logs:**
```
udp   UNCONN 0      0                                  0.0.0.0:5353       0.0.0.0:*    users:(("hb-service",pid=2145256,fd=19))
udp   UNCONN 0      0                                  0.0.0.0:5353       0.0.0.0:*    users:(("avahi-daemon",pid=2145048,fd=12))
```

**Homebridge Config:**

```json
...
"advertiser": "avahi",
...
```

**Screenshots:**
Not applicable

**Environment:**

* **Node.js Version**: 16.13.2
* **NPM Version**: 8.3.2
* **Homebridge Version**: 1.4.0
* **Homebridge Config UI X Version**: 4.42.0
* **Operating System**: Arch Linux on x64
* **Process Supervisor**: hb-service

**Comment by seidnerj** [comment]
This results in homebridge's server becoming unavailable via its .local address, usually about a day after the address is registered.

**Comment by seidnerj** [comment]
I'm back to using Ciao, can't stand having to reset Avahi every 24 hours or so. Too bad.

**Comment by ThisIsQasim** [comment]
This bug is still present, hb-service is listening for udp 5353 even though the advertiser is set to `avahi`
```
ss -ulnp | grep 5353
UNCONN     0      0            *:5353                     *:*                   users:(("hb-service",pid=337,fd=19))
UNCONN     0      0            *:5353                     *:*                   users:(("avahi-daemon",pid=32518,fd=10))
```

**Comment by peterneutron** [comment]
As long as you have no problems with your resolver or home bridge this should be fine. See https://github.com/homebridge/homebridge/issues/3077

**Comment by admo** [comment]
hb-service listens on port 5353 because the [Accessory Control](https://github.com/homebridge/homebridge-config-ui-x/wiki/Enabling-Accessory-Control) feature is enabled.
This feature is managed through homebridge-config-ui-x, where there is an option to start Homebridge in insecure mode.
Enabling it triggers a chain of Node modules: [hap-client](https://www.npmjs.com/package/hap-client) → [bonjour-service](https://www.npmjs.com/package/bonjour-service) → [mdns](https://www.npmjs.com/package/mdns).
When hb-service starts its own browser on port 5353, after a few hours the local address of the host gets lost.
I'm not sure whether this is caused by the hb-service browser or the Homebridge advertiser running in insecure mode.
Nevertheless, disabling this feature resolves the issue.
