### ISSUE TITLE
CONFIG UI HACKING

### ISSUE THREAD

**Issue by vzlgdu** [oznu/homebridge-config-ui-x#1303]
Hi, this night and again some minutes ago, my HB stopped running because someone is accessing to my network/server/configuration and modyfing it with this:

{
    "bridge": {
        "name": "Slava Ukraine! Fuck NATO!",
        "username": "CA:CA:CA:CA:CA:CC",
        "port": 51828,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": []
}

I've modified passwords and router setting.

Have someone the same problem?

**Comment by Staubgeborener** [comment]
tbh i don't think this is a real scenario because of reasons. You can check your router logs to verify this. Also, is your homebrigde instance not secured with credentials? Second, homebridge is running on a device like a server, a raspberry, etc. - also is this device not secured with credentials and a private key?

**But** what is a realistic scenario: It's not a secret, that some developers change their code according to protest against the war at the ukraine. Just take quick look for the closed issues of [node-ipc](https://github.com/RIAEvangelist/node-ipc/issues?q=is%3Aissue+is%3Aclosed). RIAEvangelist is censoring those comments right now in this minute, which is crazy. But let's not get too political here - in my opinion, the only realistic scenario are changes in code dependencies. No one would hack your router and devices to get into a small service such homebridge to change a small line of code like this (which presupposes that this person would have to know homebridge with its config structure very well). So a "individual attack" is not realistic because of all this reasons - which means, this has to be a "publicly further distributed" sort of attack.

The truth is, routers or local devices of private persons are almost never (not to say "truly never") hacked, because you are not an attractive target for such things. Since you are the only one who has noticed this so far and even searches in search engines did not yield any further insight here (to be clear: should it be a change in code dependencies, other services should also receive exactly such messages or at least similar messages). I consider all this here to be a, to say it politely, _"unrealistic scenario"_.

But yeah, in these times, every developer should check his dependencies.

**Comment by vzlgdu** [comment]
The main cause was the port 8080 opened to acces to this server (now the rule was removed).
Someone has access from this port...
Analyzing the log I found the following messages:

![image](https://user-images.githubusercontent.com/32038777/161201704-dfa8e727-aed6-434a-9b0e-25dbc6df0383.png)

**Comment by Staubgeborener** [comment]
well in this case you should also analyze the logs from your whole system not only homebridge itself

**Comment by oznu** [comment]
Closing - the UI should not be exposed to the internet and no actual vulnerability has been identified. For those that do want to "risk" it, setting a secure password and enabling 2FA is recommended.
