### ISSUE TITLE
No Status Change

### ISSUE THREAD

**Issue by kaili85** [oznu/homebridge-config-ui-x#136]
As soon as I have an additional plugin that provides not supported buttons (e.g. theater-mode for Apple TV), the switches and lights do not change the status in config-ui. But they do change the status of the devices. After reload the web-page, the correct status is shown again.

**Comment by oznu** [comment]
This is probably due to the plugin not pushing the status change and relying on the HomeKit app (or this ui) polling for the new status. The UI only requests the status once on the initial page log, subsequent status updates rely on a push.

I will add a poll request for the service after it's status is changed in the UI - soon.

**Comment by kaili85** [comment]
Sounds great, thanks for your support!
Btw: Thank you for that really great and helpful plugin!

**Comment by oznu** [comment]
All accessories states will be queried 1.5 seconds after any accessory is switched on/off via the UI as of 3.8.6.

**Comment by kaili85** [comment]
Thanks, but still no change of status as soon as there are unsupported accessories...
When I switch the page (e.g. to config) and then back to accessories, the correct status is shown.
Reinstalled the plugin to get the newest release.
