### ISSUE TITLE
"Restart" button in Homebridge UI used to invoke reboot of the Raspbery Pi, but now just restarts the Homebridge service only.

### ISSUE THREAD

**Issue by firstspencer** [oznu/homebridge-config-ui-x#1453]
### Describe The Bug

![image](https://user-images.githubusercontent.com/114834389/215879172-ee259800-cd6f-45ab-9d06-f269424a21a2.png)
In the attached image the button that I'm referring to has been identified. Clicking this used to reboot the entire Raspberry Pi, but now it only restarts the Homebridge service. I would like for it to behave as it previously did. 

### Homebridge UI Version

1.60 - not sure, see screenshot.

### Homebridge Version

1.60

### Node.js Version

18.13

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [ ] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by andrewk123** [comment]
In the three or so years I've used Homebridge, I believe that button has always worked just as it does today (restarts the homebridge application not the hardware running homebridge).  Regardless please do NOT change this feature since other applications could be running on the same platform and it makes no sense to restart the hardware (and all applications) to restart just one application.  If a user wants to reboot the hardware (in this case the raspberry pi) it's easy enough to login to the pi with ssh and do it that way.
