### ISSUE TITLE
Log files on MacOS

### ISSUE THREAD

**Issue by deon-wentzel** [oznu/homebridge-config-ui-x#161]
Hi,

Thanks for a great plugin.

Everything works fine except for the logs, I have followed the manual with no success and get the following error, 

execvp(3) failed.: No such file or directory

The log tail command "sudo -n tail -n 200 -f /Users/{name}/.homebridge/homebridge.log" exited with code 1.

My config file has the following entry

"log": {
                "method": "file",
                "path": "/Users/{name}/.homebridge/homebridge.log"
            }, 

If I copy the above command it displays correctly. I use launchctl  to start homebridge, I have also set it up to write log. The sudo option has been setup too, as listed in the instructions using visudo.

Please can you comment and point me in the right direction to resolve this issue. Thanks in advance!!!

**Comment by deon-wentzel** [comment]
If I run homebridge manually it works.

**Comment by dppeak** [comment]
@deon-wentzel did you ever figure out the way to get the logs to work with home bridge started with launchctl?

**Comment by jcharr1** [comment]
@dppeak  I had this same problem. I kept wondering why it said the file wasn't found and assumed it was because it couldn't find the log file. But it turns out that was wrong. @deon-wentzel's PATH key was the key to figuring out that the file it couldn't find was actually the `tail` command because my path for the launchctl agent didn't include `/usr/bin` where `tail` lives. Once I fixed the path and reloaded my homebridge agent, it's working fine.
