### ISSUE TITLE
Restart not working

### ISSUE THREAD

**Issue by theo-69** [oznu/homebridge-config-ui-x#23]
I start my homebridge with just homebridge (pi@raspberrypi:~ $ homebridge). I also can start with pm2 start homebridge. However it does not work!

**Comment by oznu** [comment]
Hi @theo-69,

The restart option won't work if you're not using some sort of process manager, like init.d, systemd, supervisor.d, or even pm2.

I have tested **pm2** on a Raspberry Pi and this config works:

```json
{
    "platform": "config",
    "name": "Config",
    "port": 8080,
    "log": {
        "tail": "pm2 logs --raw --lines 100 homebridge"
    },
    "sudo": true,
    "temp": "/sys/class/thermal/thermal_zone0/temp"
}
```

Then start with pm2:

```
pm2 start homebridge
```

There is no need to define a restart command since **pm2** will automatically restart the Homebridge process if it ends, which is the default behaviour for the homebridge-config-ui-x restart command.

**Comment by theo-69** [comment]
Thanks @oznu now I am getting [Config] No restart command defined, killing process...

**Comment by theo-69** [comment]
working now, one writing error ;-)

**Comment by Mrdindon** [comment]
I've added : 
 "log": {
        "tail": "pm2 logs --raw --lines 100 homebridge"
}
and homebridge starts manually by doing pm2 start homebridge
But the gui still show up "Services homebridge not started" 
Still, pressing the restart button does restart the process but then the gui stays at "restarting homebridge" until I refresh the page
Any idea ?
