### ISSUE TITLE
Failing to install the latest version

### ISSUE THREAD

**Issue by 400HPMustang** [oznu/homebridge-config-ui-x#251]
Have the latest install version of Homebridge and was trying to update config-ui-X and the install fails. Here is the debug log:

https://pastebin.com/rmZQ8cjm

Console output:
https://pastebin.com/SEbthwfV

Everything else was working until this, had no issues installing plugings. Tried rebooting, etc. No joy. If you could please help. 

Thanks,

**Comment by oznu** [comment]
The latest version of node-pty doesn't like building on < Node.js v10 on Windows I discovered recently.

If you update to Node 10 (LTS) the problem should fix itself. You will have to reinstall Homebridge and the node windows build tools if you decide to update Node.

**Comment by DJay-X** [comment]
I'm on my Raspberry Pi on node@11.13.0 | npm 6.9.0 | n@3.0.2.
I installed/updatet config-ui-x by terminal, npm install -g --unsafe-perm homebridge-config-ui-x.
Unfortunately for whatever reason, config-ui-x is not showing any plugins anymore. Just loading circle.
Everything was going well since months. Any help and idea would be appreciated.

**Comment by oznu** [comment]
Upstream issue:

```
https://github.com/Microsoft/node-pty/issues/267
```

**Comment by oznu** [comment]
Node v10+ is now required for Windows as `node-Pty` now officially requires it.
