### ISSUE TITLE
4.0.3 breaks webinterface

### ISSUE THREAD

**Issue by ronaldvans** [oznu/homebridge-config-ui-x#261]
After updating to 4.0.3 I can no longer access the web interface. The following error is logged:

Error: listen EAFNOSUPPORT: address family not supported

Reverting to 4.0.1 solved the problem

**Comment by oznu** [comment]
What OS are you using? I've tried completely disabling IPv6 on a host and can't replicate this.

**Comment by ronaldvans** [comment]
Installed on a Raspberry.

**Comment by oznu** [comment]
Thanks,

Can you try installing this pre-release to see if it solves the issue, I've added a basic check for IPv6 support before deciding to listen on `::` rather than `0.0.0.0` which I had in pre-4.0.3.

```
npm install -g --unsafe-perm homebridge-config-ui-x@next
```

Listening on `::` was documented as also listening on `0.0.0.0` for most operating systems, but it looks like it may not work at all if the OS does not have IPv6 enabled hence the `EAFNOSUPPORT`.

**Comment by oznu** [comment]
I was actually able to replicate this after disabling IPv6 using the `ipv6.disable=1` kernel parameter.

**Comment by ronaldvans** [comment]
I did an uninstall and installed the @next version. Everything is back to normal and works as expected.  Thanks for the quick action.

**Comment by oznu** [comment]
Thanks for testing. You should be able to safely upgrade to 4.0.4 now.
