### ISSUE TITLE
Thermostat display mode always off

### ISSUE THREAD

**Issue by grzegorz914** [oznu/homebridge-config-ui-x#347]
![IMG_0059](https://user-images.githubusercontent.com/28867813/62709737-40b1d380-b9f6-11e9-81ff-48ce9e7c7655.jpeg)
Hi,

Thermostat accessory mode display always “off” however it’s state is cool, heat or auto.
Also if manually change to other state always display off.

**Comment by oznu** [comment]
Can you provide screenshots and the accessory details (right click the accessory and screenshot the detailed info)

**Comment by grzegorz914** [comment]
Updated in previous post

**Comment by oznu** [comment]
Did this work previously?

I'll still need the accessories details screenshot.

**Comment by grzegorz914** [comment]
I can not make screenshots now but Current Heating Cooling State value is 0
Hovewer in HomeKit app on iPhone display Cooling

**Comment by oznu** [comment]
On initial page load; or after a page refresh, is the state displayed correctly?

**Comment by oznu** [comment]
Also, what's the value of `Target Heating Cooling State`?

**Comment by grzegorz914** [comment]
Target Heating Cooling value is 2

**Comment by oznu** [comment]
I have a theory.

The `Current Heating Cooling State` is what I use to determine the thermostat state, as I expected the thermostat plugins to update the current state when the change requested by updating the `Target Heating Cooling State` completed.

However, if as you say the UI is showing `Current Heating Cooling State` as 0 (Off) while the `Target Heating Cooling State` is 2 (Cool) then my assumptions were either wrong, or the plugin you're using didn't implement it correctly.

Which plugin are you using?

**Comment by grzegorz914** [comment]
The plugin is openHAB-complete and seems to work correct because HomeKit app display all correct.

**Comment by oznu** [comment]
Actually, I can tell from your screenshots the plugin is not implementing a thermostat correctly.

![86E0BAAC-B96C-4252-903C-C006942A4CB8](https://user-images.githubusercontent.com/3979615/62712736-c2c5ea80-ba3e-11e9-94f7-7867fa5b629e.jpeg)

The coloured circle is green. This is what is show when HomeKit has the thermostat Target state as not-off but doesn't have information about the Current state. It's usually only displayed for a moment when transitioning between states.

When implemented correctly the coloured circles go orange or blue to reflect the actual state:

![BC17F36C-B286-482A-ACDA-609BF169631D](https://user-images.githubusercontent.com/3979615/62712961-3f58c900-ba3f-11e9-9eea-bf4caf04ae29.jpeg) ![0829D1C2-9886-4460-93F5-9C42916B7B80](https://user-images.githubusercontent.com/3979615/62712962-3ff15f80-ba3f-11e9-8cea-f3e23c568280.jpeg)

However, since the Home app seems to deal with thermostats not reporting their current state, so should Homebridge Config UI X, I'll implement some changes soon.

**Comment by grzegorz914** [comment]
Ok will check this again and report back

**Comment by grzegorz914** [comment]
OK,

problem solved, create fake item in OH for current state and change its value during rule.

**Comment by oznu** [comment]
I've implemented the "green" state, where HomeKit knows the accessory is on, but has not been provided with any state information.

![image](https://user-images.githubusercontent.com/3979615/62770680-daed4680-bade-11e9-9a8d-de551f34a904.png)

![image](https://user-images.githubusercontent.com/3979615/62770710-e9d3f900-bade-11e9-8019-722444bc6d89.png)

**Comment by grzegorz914** [comment]
nice
