### ISSUE TITLE
Anything I can do about SSL support?

### ISSUE THREAD

**Issue by albi** [oznu/homebridge-config-ui-x#35]
Got a RasPi 3 running with Homebridge and Config UI X, but want to use HTTPS for the webinterface.

**Comment by oznu** [comment]
Hi @albi,

I use Nginx which acts as a reverse proxy to provide SSL support to `homebridge-config-ui-x` and several other services I have running.

There are plenty of guides on the internet showing how to set this up so I won't write up another.

I will provide the `location` block you'll need if you choose to go with Nginx though, since you need to add a few extra lines to support WebSockets which `homebridge-config-ui-x` uses heavily:

```
location / {
    proxy_pass              http://localhost:8080;
    proxy_http_version      1.1;
    proxy_buffering         off;
    proxy_set_header        Host $host;
    proxy_set_header        Upgrade $http_upgrade;
    proxy_set_header        Connection "Upgrade";
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forward-For $proxy_add_x_forwarded_for;
}
```
