### ISSUE TITLE
Log using PM2

### ISSUE THREAD

**Issue by schweppy** [oznu/homebridge-config-ui-x#460]
Hi I am using PM2 on my Pi4 to run homebridge but am struggling to work out what I need to do to setup logs in Config UI?

Current config is - 

            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"

![482482EF-3088-42D6-A7C2-0FD60955D8A3](https://user-images.githubusercontent.com/17147950/72203831-fd5a0600-3468-11ea-886d-cef8d87400dd.jpeg)

Any help would be greatly appreciated.

**Comment by oznu** [comment]
What command do you use to see the logs at the command line?

Enter the same command into the "custom" log method: https://github.com/oznu/homebridge-config-ui-x#logs-from-custom-command

---

Rather than PM2, you could give the `hb-service` command a try, this will setup Homebridge as a service to auto-start on boot and configure everything else for you. Checkout https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian) for the full instructions. Make sure you stop the pm2 service if you decide to do this.

**Comment by schweppy** [comment]
Ok will have a look. 

I’ve just tried the custom command that I normally use “pm2 logs homebridge”

However get this - 

![4C823053-2C27-4725-B781-D0DCB68946F6](https://user-images.githubusercontent.com/17147950/72204141-a9512080-346c-11ea-8193-2c5be70eb946.jpeg)

**Comment by oznu** [comment]
The capital P in `pm2` might be breaking that.

**Comment by schweppy** [comment]
Correct!!!! Thank you so much. All working!
