### ISSUE TITLE
Temp 0.00°C 

### ISSUE THREAD

**Issue by gtrnz** [oznu/homebridge-config-ui-x#5]
Temperature shows as 0.00°C with this plugin
The regular homebridge-config-ui by shidevil works fine, tried specifying       
"temp": "/sys/class/thermal/thermal_zone0/temp",
But no luck.

**Comment by oznu** [comment]
What does it show in the homebridge logs when you refresh this page?

**Comment by halpls** [comment]
How might I do that?

**Comment by oznu** [comment]
Made some changes.

* If the `temp` config option is not defined the temp status will not show up at all rather than just showing "0.00°C".

* The log output will now display an error if the path specified in the `temp` does not exist:

```
[1/9/2018, 6:08:04 PM] [Config] Initializing config platform...
[1/9/2018, 6:08:04 PM] [Config] ERROR: Path to temp file does not exist: /sys/class/thermal/thermal_zone0/temp
[1/9/2018, 6:08:04 PM] [Config] ERROR: CPU Temp will not be displayed
```

* If the system fails to read the temp file or fails to parse current temperature an error will be displayed in the log file but it won't crash Homebridge anymore.

Tested and working on a Raspberry Pi 3:

![image](https://user-images.githubusercontent.com/3979615/34709651-274dda38-f56c-11e7-8ee8-65f4c6b50881.png)
