### ISSUE TITLE
Remove built in Web Server

### ISSUE THREAD

**Issue by memphis2k** [oznu/homebridge-config-ui-x#504]
Hello,

I'm running Ubuntu Server 18.04 and have Apache running.  When I install homebridge-config-ui-x, it installs its own web server.  Is there any way I can disable this and just run everything under Apache / 443?  The reason I am asking this is I'm having problems getting Let's Encrypt certs to work with the built-in web-server.  

Can't get homebridge-config-ui-x to start properly.
`
            "ssl": {
            "key": "/etc/letsencrypt/archive/*.*/privkey5.pem",
            "cert": "/etc/letsencrypt/archive/*.*/fullchain5.pem"
            },`

**Comment by oznu** [comment]
Hi @memphis2k,

You can reverse proxy from Apache to the built in web server, however is not possible to just use apache since that's not how Node.js works.

See https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Apache for a basic template that will get you started on setting up a reverse proxy in apache. If you use this method you will be able to use Apache to handle the SSL side of things and can remove the ssl config from your homebridge config.json.
