### ISSUE TITLE
Homebridge config UI X doesn't show correct version of node installed

### ISSUE THREAD

**Issue by redeemer666** [oznu/homebridge-config-ui-x#506]
Server page tells me I have 9.9.0 installed, but I'm using v 13.7.0 as logged by "node -v" command

**Comment by oznu** [comment]
Hi @redeemer666,

Assuming you have restarted the UI since updating Node.js; this means you have multiple versions of Node.js installed on your system. The process version shown in the UI is the Node.js version the service started with.

Please refer to the way you originally installed Node.js and ensure you install the updated version of Node in the same way.
