### ISSUE TITLE
Restart script not working

### ISSUE THREAD

**Issue by genfersee** [oznu/homebridge-config-ui-x#511]
Dear all,
I am launching homebridge in the following way:
screen -dmS homebridge sh /home/pi/.homebridge/launcher.sh

I defined a bash script restart.sh which is called via the UI by executing:
sh /home/pi/.homebridge/restart.sh
The final part of the script is not executed. Is there a way to see the logs when this restart script is launched by the UI? When launched manually, the script works great...

Thanks in advance :)

**Comment by kimme1024** [comment]
I'm also using screen to run my homebridge service...
When using the restart button it terminates the process but it doesn't restart it...

A solution for this would be great!

**Comment by genfersee** [comment]
My restart script kills the screen in which current homebridge was running.
Then the script is supposed to create a new screen with new instance of homebridge, but this does not work, no screen is created.

**Comment by oznu** [comment]
Hi @genfersee,

Using the restart script in screen this way will not work. This is due to the script itself being killed before the "start" portion of the scrip can be executed.

Consider using systemd or another real process supervisor.

See https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian) for a quick method of getting a systemd service installed.
