### ISSUE TITLE
Multiple Instances Of Homebridge Found Installed - /usr/local/Cellar/node/12.12.0/lib/node_modules/homebridge

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#513]
@oznu I hope you are doing well also in the new year and everything is fine. All the best to you.

I am a little lost with this recent problem.
I run Homebridge on my iMac for a long time now. Mostly only with config-ui-x and homebridge-music plugin to control iTunes/Apple Music.

macOS 10.15.3, homebridge@0.4.50, node@12.14.1, npm@6.13.6, config-ui-x@4.9.0

Everything is working great except the latest message in the log.
I'm not aware of "multiple instances" on my Mac and the biggest confusion that the log is pointing to Node 12.12.0. I'm running Node 12.14.1
Could the update to the lates node the problem and how to fix this?

As mentioned everything is working well but the log entry bothers.
Removing just the folder /usr/local/Cellar/node/12.12.0/ killed homebridge. I copy/paste all files back and it works again.

Thanks in advance for any help.

```
[1/29/2020, 9:06:18 PM] [Config] Homebridge Config UI X v4.9.0 is listening on :: port 8080
[1/29/2020, 9:06:35 PM] [Config] Multiple Instances Of Homebridge Found Installed
[1/29/2020, 9:06:35 PM] [Config] /usr/local/Cellar/node/12.12.0/lib/node_modules/homebridge
[1/29/2020, 9:06:35 PM] [Config] /usr/local/lib/node_modules/homebridge
[1/29/2020, 9:10:06 PM] [Config] Multiple Instances Of Homebridge Found Installed
[1/29/2020, 9:10:06 PM] [Config] /usr/local/Cellar/node/12.12.0/lib/node_modules/homebridge
[1/29/2020, 9:10:06 PM] [Config] /usr/local/lib/node_modules/homebridge
```

**Comment by Neejoh** [comment]
Not my place to say anything about this but I *think* HomeBrew is maintaining your installs and versions. Any chance you used that to install Homebridge?

A description how to read through the HomeBrew logs can be found [here](https://apple.stackexchange.com/questions/83827/where-does-homebrew-log/83839).

My best guess would be to take that route, and check HomeBrew for what's going on.

**Comment by oznu** [comment]
Run this to find the path that should be used:

```
npm -g prefix
```

Then check your homebridge binary location to see if it matches:

```
ls -l $(which homebridge)
```

Are you using launchctl to start homebridge? If so check the `.plist` file to see the start path.

**Comment by DJay-X** [comment]
Hmm... 
`npm -g prefix` is pointing to 12.12.0

To launch using `launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/homebridge</string>
             <string>-I</string>
        </array>
    <key>StandardOutPath</key>
        <string>/Users/daniel/.homebridge/homebridge.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/daniel/.homebridge/homebridge.log</string>
    <key>EnvironmentVariables</key>
        <dict>
        <key>PATH</key>
            <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
            <string>/Users/daniel</string>
        </dict>
</dict>
</plist>
```

```
daniel@iMac ~ % npm -g prefix
/usr/local/Cellar/node/12.12.0
daniel@iMac ~ % ls -l $(which homebridge)
lrwxr-xr-x  1 daniel  admin  45 Oct 19 23:27 /usr/local/bin/homebridge -> ../lib/node_modules/homebridge/bin/homebridge
```

**Comment by oznu** [comment]
What about this?

```
ls -l $(which hb-service)
```

**Comment by DJay-X** [comment]
% ls -l $(which hb-service)
ls: found: No such file or directory
ls: hb-service: No such file or directory
ls: not: No such file or directory

**Comment by oznu** [comment]
Hmmm there is something off about your node/npm setup (probably due to installing/updating Node.js using different methods), without risking breaking your install I'm not sure how to proceed.

The homebridge check is really only to load the current version of the Homebridge module, so it's not that big a deal right now.

If you want to try and fix it, I would start by trying to remove all copies of Node.js/npm and start fresh (no need to delete any Homebridge config).

**Comment by oznu** [comment]
updated comment above with possible solution

**Comment by DJay-X** [comment]
Thanks for your friendly help. I'll give it a try after I'm back from vacation. At least everything is running independent from this warning message.
I close this issue, because it seems only a problem at my end. 
Thanks again. I appreciate the time you are investing.

**Comment by richierockskool** [comment]
I have sort of the same problem where HB it not loading...getting these warnings and errors
Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway-platform' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-inkbird-gateway'.

ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[7/1/2022, 5:22:49 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-inkbird-gateway/src/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:141:22)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:5)
[7/1/2022, 5:22:49 PM] ====================

No plugin was found for the platform "HomebridgeInkbirdWifiGateway" in your config.json. Please make sure the corresponding plugin is installed correctly.

I ran npm -g prefix 

npm -g prefix
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
/usr/local

and then

ls -l $(which homebridge)
lrwxr-xr-x  1 root  admin  45 Jun 29 18:14 /usr/local/bin/homebridge -> ../lib/node_modules/homebridge/bin/homebridge

How do I proceed to correct this?

**Comment by richierockskool** [comment]
Still have the same issue...

sudo npm install -g homebridge-inkbird-wifi-gateway 

and getting the same errors

**Comment by richierockskool** [comment]
I have corrected all errors and no bugs are showing anymore but still this ...
No plugin was found for the platform "HomebridgeInkbirdWifiGateway" in your config.json. Please make sure the corresponding plugin is installed correctly

/usr/local/bin/hb-service -> ../lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js

Is this how to find it?
