### ISSUE TITLE
accessories won't show up

### ISSUE THREAD

**Issue by RSMBS** [oznu/homebridge-config-ui-x#54]
I run the command homebridge -I and tried much but the accessory tab won't show up in the web interface

**Comment by oznu** [comment]
Hi @RSMBS,

Can you manually navigate to the `/accessories` page, for example http://localhost:8080/accessories, and then provide the homebridge log output after going to this page?

**Comment by iShift** [comment]
+1 i have same issue, i have no link but if i open link manual - it opens.

but on that page i have not any device from home bridge...

**Comment by oznu** [comment]
Hi @iShift,

Can you provide the homebridge log output after you go to this page manually?

**Comment by iShift** [comment]
@oznu my fail, "[Config] Homebridge must be running in insecure mode to view and control accessories from this plugin."
sorry...

**Comment by iShift** [comment]
hmm, i add -I to my system script and restart home bridge => then i can open /accessories page, (manual, no link in menu), but, after that - i get link...

**Comment by oznu** [comment]
I think @RSMBS might have another problem, since he is starting homebridge with `-I` yet it's still not working. Seeing the logs from that setup will help fix this issue.

The error message you got is only shown when Hombridge responds with a 401 (Authentication Required) response, which only happens when Hombridge is not running in insecure mode.

https://github.com/oznu/homebridge-config-ui-x/blob/master/src/wss/accessories.ts#L67

A full page refresh is needed after enabling insecure mode for the menu item to show up.

**Comment by iShift** [comment]
sorry for off topic, but can homebridge get access to original homekit accessory?

**Comment by oznu** [comment]
> sorry for off topic, but can homebridge get access to original homekit accessory?

It can't. Once an accessory is paired with HomeKit the encryption used makes in practically impossible to control the accessory using HAP from any non-iOS device.

**Comment by oznu** [comment]
Hi @RSMBS, are you still having trouble with this?

**Comment by oznu** [comment]
Please reopen if you're still experiencing issues.
