### ISSUE TITLE
[Enhancement] Show homebridge instance name in Window Title

### ISSUE THREAD

**Issue by meluvalli** [oznu/homebridge-config-ui-x#547]
Currently when running node in Windows, the window title just shows "homebridge-config-ui-x".  Would be nice if it could show the instance name or "name" property from config file.

![image](https://user-images.githubusercontent.com/8729476/74841677-a90b3700-52ee-11ea-95f0-d42fee3e8849.png)

**Comment by oznu** [comment]
This won't be possible sorry, the process title needs to be "homebridge-config-ui-x" as this is used on other platforms (like docker).

Rather than running Homebridge in a terminal window have you considered running as a service?

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-on-Windows-10

Homebridge Config UI X provides a service helper that supports multiple instances.
