### ISSUE TITLE
Configuration Screen doesn't show "Server" information on the left side

### ISSUE THREAD

**Issue by halpls** [oznu/homebridge-config-ui-x#6]
Only "Platforms" view is shown

**Comment by oznu** [comment]
I'm not sure where you are seeing this. My fork does not have any "Platforms" view - it just has the config.json editor which allows you to edit server information, platforms and accessories directly.

I removed the "Simple" editor from that was in the original project because it was buggy and not really that helpful as you still had to edit json.
