### ISSUE TITLE
Advanced stats

### ISSUE THREAD

**Issue by iShift** [oznu/homebridge-config-ui-x#61]
i found that script, it shows cool stats for raspberry, maybe add support for advanced stats in UI?
useful if you have homebridge cameras and you want to watch raspberry load
https://github.com/MilhouseVH/bcmstat
![2018-03-18 11 54 26](https://user-images.githubusercontent.com/426427/37564286-ad870a36-2aa3-11e8-97df-fe8abbf425c4.png)

**Comment by oznu** [comment]
Hi @iShift,

This would be interesting to add, however at the moment I'm trying to be as platform agnostic as possible - with the main exception being special features for users running this in the [oznu/homebridge](https://github.com/oznu/docker-homebridge) docker image; as well as a few lines of code to make it Windows 10 compatible.

The existing cpu and memory stats are exposed by the [node.js api](https://nodejs.org/api/os.html#os_os_loadavg) which is why I have been able to included them.
