### ISSUE TITLE
Updated plugins as global?

### ISSUE THREAD

**Issue by realdannys** [oznu/homebridge-config-ui-x#743]
Hi,

Running the latest version of everything - when I use config-ui-x to update a plugin from the interface it does so with the -g command where as I install all my plugins globally (which is usually the default installation string anyway) why is this and is there anyway we can ensure updates are run globally?

**Comment by oznu** [comment]
Hello @realdannys,

The UI will attempt to update plugins in the same location they are already installed in.

Sometimes users have multiple global modules folders due to configuration issues (`/usr/local/lib/node_modules` or `/usr/lib/node_modules` for example) and this ensures the plugin is updated rather than installed again in a different location.

npm figures out we are installing gobally when the cwd is a global install location, there is also an environment variable set to tell npm we are installing globally.

Is this not working for you?

**Comment by realdannys** [comment]
Hi @oznu 

I've always installed everything with -g and i usually just do it from the command line as I find I can control it better but tried the UI again today - it ran my update as` [Config] Running Command: npm install homebridge-tahoma@latest ` i'd have expected to see `npm install -g homebridge-tahoma@latest` would it just not show the -g in the log?

**Comment by oznu** [comment]
Yes that's correct, it's still installing it globally.

**Comment by realdannys** [comment]
Excellent, thanks for your clarification!
