### ISSUE TITLE
Purge Logs?

### ISSUE THREAD

**Issue by charona** [oznu/homebridge-config-ui-x#888]
My log files are filling up the SD / after about a year. Does anybody know of a plugin or any other way to automatically purge the log files from time to time? I can do it with SSH, but then I will always forget until it's too late.

PS I love this web interface. Great work.

**Comment by oznu** [comment]
If you use `hb-service` as the process supervisor the logs are purged automatically - every 4 hours of above 2MB in size.

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command

When using hb-service, there is also a button in the UI to truncate / purge the logs on demand.

Otherwise checkout the logrotate utility.

**Comment by charona** [comment]
Thanks a lot. How do I know if I'm using hb-service? I installed the Pi some 2 years ago I think, and really can't remember what I chose back then. Pardon my ignorance :)

**Comment by oznu** [comment]
You aren't - your logs would be being truncated and it only came out in Jan 2020.

If you want too, make sure you remove your existing service first, and take a backup in case you need to restore - https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

**Comment by charona** [comment]
That's some great and fast help. Thanks!
