### ISSUE TITLE
Unable to connect to CCU3

### ISSUE THREAD

**Issue by khwerhahn** [oznu/homebridge-config-ui-x#934]
**Describe Your Problem:**

I setup the config and hombridge restarts and in the logs spit out the following:

**Logs:**
![grafik](https://user-images.githubusercontent.com/3821617/98228617-1af8de80-1f59-11eb-9369-3f0339ebb496.png)

**Homebridge Config:**
![grafik](https://user-images.githubusercontent.com/3821617/98228194-8c845d00-1f58-11eb-8515-ebc60aa5fc69.png)

**Environment:**
![grafik](https://user-images.githubusercontent.com/3821617/98228782-5abfc600-1f59-11eb-8c5a-d9a2562237ed.png)

**Comment by oznu** [comment]
Hi @khwerhahn,

It looks like you're not running Homebridge, and this project is for the Homebridge UI.

If you'd like to swap to Homebridge, you can backup your HOOBS instance and restore it into Homebridge:

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge

Otherwise, you will need to contact HOOBS support directly for any assistance.
