### ISSUE TITLE
Update failure

### ISSUE THREAD

**Issue by ragacs** [oznu/homebridge-config-ui-x#948]
I've installed this node module into a home directory of a local user account (without -g option) and using it for several years on a Linux machine. Updating from UI worked well countless times but recent versions broke this functionality because it always specifies the -g option regardless of the Sudo setting (it is turned off as you guessed). I had to do it from the console. Could somebody fix this issue?

**Comment by oznu** [comment]
Start Homebridge with the `-P <path to plugin folder>` flag.

**Comment by bdruth** [comment]
fwiw, since this took me a solid half hour to sort out, the `<path to plugin folder>` is the `node_modules` directory that homebridge and it's plugins are installed in. E.g., I have a `homebridge` local user setup, running out of `/var/lib/homebridge`, which is where `config.json`, `accessories`, `persist`, and (of course) `node_modules` is ... I also keep a `package.json` here, which is updated when plugins are updated. So, in this case, I added `-P /var/lib/homebridge/node_modules` in addition to the `-U /var/lib/homebridge` that I already had there ... this seemed to do the trick in telling `homebridge-config-ui-x` to stop trying to `nom install -g` everything.
