### ISSUE TITLE
NSP Error

### ISSUE THREAD

**Issue by suxus-zz** [oznu/homebridge-config-ui-x#95]
Hello
I have a Raspberry Pi and when i type this command

npm list -g --depth=0

then i have at the end this error.

ERR! extraneous: nsp@3.2.1 /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/nsp

Is this a error from the ui-x Plugin, when yes what's wrong?

Greeting

**Comment by oznu** [comment]
It would be caused by `homebridge-config-ui-x`.

I removed the `nsp` module in the most recent patch, but due to the way the self-update process works, the update to this version would have failed as the `nsp` tool would was removed from disk. To solve this problem I "faked" the `nsp` tool so users could upgrade without any alarming errors being displayed.

It's generated using this post-install script:

https://github.com/oznu/homebridge-config-ui-x/blob/master/src/bin/fake-nsp.ts

It will be removed in the next major version. For now, nothing is wrong, it's working as intended.

You can delete the `/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/nsp` directory now if you want, it's not going to get used again.

**Comment by oznu** [comment]
I might actually push up a new release that will cleanup the "fake" `nsp` module on the first run of the updated version.

**Comment by suxus-zz** [comment]
Okay, thank you. At the moment i make nothing and wait for the new release.

Thank you

**Comment by oznu** [comment]
On second thoughts, I think it's best to delete the `/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/nsp` directory yourself if you want the error to go away.

Deleting the directory at run time will require privileged (root) permissions or for me to use the `sudo` command. I don't think it's a good idea to start using the `sudo` command to delete stuff outside the homebridge user directory without the users express permission.

I will remove the fake nsp generation script in the next major release (semver major, breaking changes allowed).
