### ISSUE TITLE
hb-service logs -S // problem with upper case directory

### ISSUE THREAD

**Issue by DJay-X** [oznu/homebridge-config-ui-x#964]
Hey there. Hope you are well. @oznu 

I switched from systemd to hb-service with my homebridge and 2nd-Instance.
Everything worked very well thanks to your [instruction](https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Swap-From-Standalone-Mode-to-Service-Mode).

However, when I want to check the log via terminal for the 2nd-Instance the log is not showing up.

$ sudo hb-service logs -S homebridge-2nd-Instance
✖ ERROR: Log file does not exist at expected location: /var/lib/homebridge-2nd-instance/homebridge.log

In the folder  /var/lib/homebridge-2nd-**I**nstance/ (upper case I) there is a homebridge.log and with the Config UI everything is showing up as expected.

The problem seems that sudo hb-service logs -S homebridge-2nd-Instance is pointing to the directory with lower case i.

I hope you can help. Did I do something wrong? However, everything seems to run good.

Thanks in advance.

**Comment by oznu** [comment]
Hi @DJay-X,

Thanks for raising this. I have encountered an issue while looking into this.

Generally, users can create a new instance by passing in a service name, such as `homebridge-TWO` or `homebridge-2nd-Instance` and the service name is forced to be lowercase.

eg. both these commands will result in exactly the same thing, with the path being `/var/lib/homebridge-two`:

```
hb-service install --service-name homebridge-TWO
hb-service install --service-name homebridge-two
```

If I were to change the log viewing command to not lower case the service name, existing users expecting `hb-service install --service-name homebridge-TWO` to work even though the path is lowercase, would be impacted.

---

In your case, you can still view the logs by passing the directory path instead of the service name. eg.:

```
hb-service logs -U/var/lib/homebridge-2nd-Instance
```

---

It might be easier to just change the directory to be lowercase 😄

**Comment by DJay-X** [comment]
> It might be easier to just change the directory to be lowercase 😄

Thanks for your reply. 
So I just can rename the directory in my case to /`var/lib/homebridge-2nd-instance `manually without breaking anything?

That would of course be the easiest way 😅 But just to be sure.
Thanks again.

And of course for everything you share with the community. 🙏

**Comment by oznu** [comment]
ok, so first remove the service:

```bash
sudo hb-service uninstall homebridge-2nd-Instance
```

Then change the folder name to lowercase:

```bash
mv /var/lib/homebridge-2nd-Instance /var/lib/homebridge-2nd-instance
```

Then recreate the service, no need to specify the path, as `-S homebridge-2nd-instance` will automatically set the storage directory as `/var/lib/homebridge-2nd-instance`:

```bash
# replace --user homebridge with the user you run the service as
sudo hb-service install -S homebridge-2nd-instance  --user homebridge
```

Done.

Can't hurt to do a [backup](https://github.com/homebridge/homebridge/wiki/Backup-and-Restore) first.

**Comment by DJay-X** [comment]
That did work. 👍 Thanks for your time and helping/fixing this issue. 
I don't want to miss what you do with your work for the community and the perfect Homebridge Home anymore ;) 
Big thank you. Take care.

**Comment by oznu** [comment]
Thanks 😄 

I'm glad you got it sorted.
